### ISSUE TITLE
[BUG] Invisible tokens not visible to DM in combat tracker

### ISSUE THREAD

**Issue by MrPotatoZed** [averrin/director#1]
**Module Version:** v0.2

**Describe the bug**
With only director and dependencies active when tokens are invisible they are not visible at all in the combat tracker and cannot be interacted with by the DM. Similarly, when using the toggle visibility button in the tracker it makes the token completely invisible instead of merely making them transparent and not visible to players. Normally invisible tokens are added as invisible to players but are visible to DMs. Without director activated tokens appear as expected in the tracker. No errors in console. See video below. 

Tested in v9.269, 5e 1.6.3, using chrome and firefox, hosted on the forge. 
![director](https://user-images.githubusercontent.com/85974617/176328760-02589d7e-efeb-481e-bd40-1ed416e5363c.gif)

Thanks for your work on this and looking forward to the sequencer functionality.

**Comment by averrin** [comment]
This is sooooo weird. I dont know how its possible. But, yes, Director causes it. I'll investigate it in a couple of days, thanks.

**Comment by MrPotatoZed** [comment]
Confirmed this is working for me as well after the newest release. Thanks for the quick fix.
