### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by Crowguard** [averrin/director#3]
Error that occurs after adding a "random rotation" to this sequence. 

![image](https://user-images.githubusercontent.com/99844555/189036798-588b613e-8111-420c-8b27-b117eb0ec542.png)

![image](https://user-images.githubusercontent.com/99844555/189036736-8d98a0ec-12f4-4076-8855-4195127a0cd0.png)

![image](https://user-images.githubusercontent.com/99844555/189036866-37e1c68b-f3f3-4c3a-904a-dbf60ab16731.png)

**Comment by averrin** [comment]
I hope it was fixed in https://github.com/averrin/director/releases/tag/0.9.1
Please reopen if not.
