### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Truncated** [averrin/director#6]
**Module Version:** v1.0.0
**Describe the bug**
Drop down for Action type shows below the main window (z-index too low).

**To Reproduce**
1. Open Director
2. Make new action
3. Click on Type drop-down

**Expected behavior**
Dropdown shows above configuration screen pop-up so that type can be selected.

**Screenshots**
![image](https://user-images.githubusercontent.com/14208325/203207402-808a17c7-4220-4769-8a3c-3ba1fdf4ea64.png)

**Browser:**
Chrome

**Foundry Version:** 
v10.290

**Game System:** 
PF1 v0.82.0

**Additional context**
Target Drop-down and others likely suffer the same problem. I only tested hooks and actions before I figured it was widespread enough and likely just one setting for all of them.

**Comment by averrin** [comment]
Oh, shit. Looks like you lost all css styles... could you please test with only director enabled?

**Comment by Truncated** [comment]
No dice. :(
![image](https://user-images.githubusercontent.com/14208325/203439685-efbe036d-ecb4-49be-94e5-d6a03f97239c.png)

**Comment by averrin** [comment]
I hope this one is fixed.

**Comment by Truncated** [comment]
Looks fixed on my side!
![image](https://user-images.githubusercontent.com/14208325/204114356-5b4df7e5-a8e0-471e-9714-2e08fcff705f.png)
